[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "statisQ"
version = "0.1.0"
description = "Terminal-based system resource monitor"
requires-python = ">=3.10"
dependencies = [
    "psutil>=7",
]

[project.scripts]
statisQ = "statisQ.core:main"

[tool.setuptools.packages.find]
where = ["src"]
